### ISSUE TITLE
[definition list] Markdown Support?

### ISSUE THREAD

**Issue by mmcky** [executablebooks/sphinx-tomyst#18]
Markdown support is limited for `definition list` items. 

```rst
definition_list
---------------

This tests `definition`, `definition_list` and 
`definition_list_item`

Term
  Definition.

Term : classifier
    The ' : ' indicates a classifier in
    definition list item terms only.
```

https://meta.stackexchange.com/questions/72395/is-it-possible-to-have-definition-lists-in-markdown

The options are:

1. add warnings to `myst` converter advising no direct representation in markdown and skip nodes
1. add as `html` for markdown (but creates difficulties for `pdf` support)
1. add as markdown with `mimic` spacing
1. write a definition list directive for sphinx that `myst` can call

**Comment by pradyunsg** [comment]
MyST now supports definition lists: https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html#definition-lists

**Comment by mmcky** [comment]
oh great - thanks for the link @pradyunsg
